use_frameworks!

platform :ios, '9.0'

target 'Lottie3ObjcWrapper_Example' do
  pod 'Lottie3ObjcWrapper', :path => '../'

  target 'Lottie3ObjcWrapper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
